import Head from "next/head";
import Image from "next/image";
import EvenList from "@/components/events/event-list";
import styles from "@/styles/Home.module.css";
import { getFeaturedEvents } from "../../dummy-data";

export default function Home() {
  const featuredEvents = getFeaturedEvents();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <EvenList items={featuredEvents} />
      </main>
    </>
  );
}
